@baseUrl = http://localhost:3333
# @baseUrl = https://noxpay.onrender.com
@cryptoId = e5eef93a-40f0-40b2-883d-c01e720b107c
# @name list_all_cryptocurrencies
GET {{baseUrl}}/cryptocurrency
Content-Type: application/json

###

# @name update_cryptocurrency_votes
PUT {{baseUrl}}/cryptocurrency/{{cryptoId}}/vote
Content-Type: application/json

###

# @name create_cryptocurrencies
POST {{baseUrl}}/cryptocurrency
Content-Type: application/json

{
  "name": "bitcoin",
  "price": 123
}

